trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: Internal_build_testing
  displayName: Internal build testing
  jobs:
  - job: Update_dependencies
    displayName: Update dependencies
    pool:
      vmImage: $(defaultWindows1809PoolImage)
    steps:
    - powershell: >
        pwsh
        -Command "$(engPath)/Get-DropVersions.ps1
        -BuildId 2525144
        -InternalArtifactsAccessToken $(System.AccessToken)
        -updatedependencies
        -UseInternalBuild"
      displayName: Update dependencies and dockerfiles
    - script: cat ./src/runtime/9.0/nanoserver-ltsc2022/amd64/Dockerfile
      displayName: Print sample dockerfile
