trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/core.yml@self
- name: officialBranches
  # comma-delimited list of branch names
  value: nightly

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - stage: Generate_Build_and_Test
      displayName: Generate Build and Test
      jobs:
      - job: Update_Dockerfiles
        displayName: Update dockerfiles
        pool:
          name: NetCore1ESPool-Internal
          image: 1es-windows-2022
          os: windows
        steps:
        - pwsh: >
            ./eng/Get-DropVersions.ps1
            -BuildId 2525144
            -InternalArtifactsAccessToken $(System.AccessToken)
            -updatedependencies
            -UseInternalBuild
          displayName: Update dockerfiles
