trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: Generate_Build_and_Test
  displayName: Generate Build and Test
  jobs:
  - job: Update_Dockerfiles
    displayName: Update dockerfiles
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
      parameters:
        setupImageBuilder: false
        setupTestRunner: true
        cleanupDocker: true
    - template: /eng/common/templates/steps/run-pwsh-with-auth.yml@self
      parameters:
        displayName: Azure login
        serviceConnection: $(test.serviceConnectionName)
        command: >
          $azLoginArgs = '--service-principal --tenant $env:tenantId -u $env:servicePrincipalId --federated-token $env:idToken';
          $(engCommonRelativePath)/Invoke-WithRetry.ps1
          "az login $azLoginArgs"
    - powershell: |
        $args = @{
          BuildId = "2525144"
        }

        $args["InternalArtifactsAccessToken"] = "$(System.AccessToken)"
        $args["updatedependencies"] = $true
        $args["UseInternalBuild"] = $true

        $(engPath)/Get-DropVersions.ps1 @args
      displayName: Update dependencies and dockerfiles
