trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: Generate_Build_and_Test
  displayName: Generate Build and Test
  jobs:
  - job: Update_Dockerfiles
    displayName: Update dockerfiles
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - powershell: |
        $args = @{
          BuildId = "2525144"
        }

        $args["InternalArtifactsAccessToken"] = "$(System.AccessToken)"
        $args["updatedependencies"] = $true
        $args["UseInternalBuild"] = $true

        $(engPath)/Get-DropVersions.ps1 @args
      displayName: Update dockerfiles
