trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: Generate_Build_and_Test
  displayName: Generate Build and Test
  jobs:
  - job: Update_Dockerfiles
    displayName: Update dockerfiles
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
      parameters:
        setupImageBuilder: false
        setupTestRunner: true
        cleanupDocker: true
    - template: /eng/common/templates/steps/run-pwsh-with-auth.yml@self
      parameters:
        displayName: Azure login
        serviceConnection: $(test.serviceConnectionName)
        command: >
          az login --service-principal --tenant $env:tenantId -u $env:servicePrincipalId --federated-token $env:idToken
    - powershell: >
        pwsh
        -Command "./eng/Get-DropVersions.ps1
        -BuildId 2525144
        -InternalArtifactsAccessToken $(System.AccessToken)
        -updatedependencies
        -UseInternalBuild"
      displayName: Update dependencies and dockerfiles
